---
ascii-movie:
  fullnameOverride: cit1-test-test-test

  env:
    ASCII_MOVIE_TELNET_ENABLED: false
    ASCII_MOVIE_SSH_ENABLED: false

  service:
    main:
      ports:
        http:
          enabled: true
          primary: true
          port: 80
        ssh:
          enabled: false
        telnet:
          enabled: false
    api:
      enabled: false

