---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: whoami
  namespace: argocd
  labels:
    app: whoami
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # roles:
  # - name: "project-admin"
  #   policies:
  #     - "p, proj:whoami:project-admin, applications, update, whoami/*, allow"
  #     - "p, proj:whoami:project-admin, applications, sync, whoami/*, allow"
  #     - "p, proj:whoami:project-admin, applications, get, whoami/*, allow"
  #     - "p, proj:whoami:project-admin, applications, override, whoami/*, allow"
  #     - "p, proj:whoami:project-admin, repositories, get, whoami/*, allow"
  #   groups:
  #   - res_paloalto_prodops
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: "*-whoami"
    server: "*"
  sourceRepos:
  - "https://github.com/xadcoh/argocd.git"
